AllCops:
  RunRailsCops: true
  Exclude:
    - 'tmp/**/*'
    - 'cookbooks/**/*'
    - 'app/models/ability.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form*.rb'
    - 'Cheffile*'
    - 'bin/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
Documentation:
  Enabled: false
TrailingBlankLines:
  EnforcedStyle: final_blank_line
ClassLength:
  Max: 120
MethodLength:
  Max: 12
LineLength:
  Max: 85

