AllCops:
  RunRailsCops: true
  Exclude:
    - 'tmp/**/*'
    - 'cookbooks/**/*'
    - 'app/models/ability.rb'
Documentation:
  Enabled: false
TrailingBlankLines:
  EnforcedStyle: final_blank_line
ClassLength:
  Max: 120
MethodLength:
  Max: 12
LineLength:
  Max: 85

